### ISSUE TITLE
Speed up imaging

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/bayes_gain_screens#15]
By subtracting sources outside primary beam and truncating the preapplied dico model, mask, and appropriately setting image size.

**Comment by rvweeren** [comment]
Yes, we could subtract sources -outside- a square region covering approximately up to 0.3 of the primary beam attenuation. The DDS3 solutions should be perfect for that. Then the screen imaging will be quicker and we can use more "screen facets" since we do not run into memory issues on herts.

**Comment by cyriltasse** [comment]
Ok - just added the option `NPixOut` to `MaskDicoModel`. This will enable to produce the 3 DicoModel you need:

- The 20k one with the faint sources
- The 10k one with the bright sources for `kMS` calibration
- The 10k one with all inner sources for DDFacet reimaging

For producing the shrinked DicoModel just use:

`MaskDicoModel.py ... --NPixOut <Whatever>`

Whatever will be adapted to what DDFacet is internally using for optimal FFT, so any number is good enough

**Comment by cyriltasse** [comment]
The updated version is available on the `gain_screens_premerge` `DDFacet` branch

**Comment by Joshuaalbert** [comment]
Thanks @rvweeren this means now the only thing left is to make another column of "DATA_SUB_OUTER" during the subtract step.

**Comment by rvweeren** [comment]
Yes, we need one more column.

**Comment by cyriltasse** [comment]
You need two subtract step no? One where you remove all but the brightest sources, and one where you remove only the outer sources?

**Comment by Joshuaalbert** [comment]
Yes, it should be a simple addition. Will tackle this tomorrow.

**Comment by Joshuaalbert** [comment]
I pushed code to do subtraction. We should discuss some good numbers for image parameters then.  Currently I subtract all sources outside a radius of npix/4. This means that we keep the inner npix/2 sources, where npix is the width of the archival image (20000). 

So what happens if I specify `MaskDicoModel.py ... --NPixOut 10000` and then image with `--Image-NPix=12000`. @cyriltasse said that the dico will be adapted, but should this number match what I pass to DDFacet? Would I then need to specify the same number to both `MaskDicoModel` and `DDF`?

Secondly, what is a good choice for image size? 10000 would make the image 4 times smaller, but what region will we do science with?

**Comment by Joshuaalbert** [comment]
@rvweeren ^

**Comment by Joshuaalbert** [comment]
Also, how can crop the mask file? If DDFacet internally changes npix to match FFT sizes, then I do not know the proper output shape for the mask. Also, even if I did know the mask shape, I wouldn't know the WCS to relate pixels to world coords. The ideal situation would be that I create a ds9 region file that denotes the region that we want to image, and then one single command filters the dico model, crops the mask, and determines the image output shape.

**Comment by rvweeren** [comment]
I think you do not have to worry about DDFacet internally changing npix (you just work like it does not happen and DDFacet automatically handles that)

**Comment by rvweeren** [comment]
If you crop --NPixOut 10000 just image with --NPixOut 10000, that makes life easier.

**Comment by cyriltasse** [comment]
Yes, if you chose `--NPixOut 10000` in `MaskDicoModel`, then use `--Image-NPix 10000` in `DDFacet`, and the magic will internally happen... You can try to use the same mask (the 20000x20000 one), I think  it should automatically crop it to the right dimentions, but I've not used that for a long time and this might be broken. If so, let me know and I'll fix...

**Comment by Joshuaalbert** [comment]
@cyriltasse I looked into the `MaskDicoModel` file at the modelifications and it looks like the `NPixOut` only changes the image size. However, I still have the problem of supplying my own mask to filter the Dico components. The mask should coincide with the same region selected by `NPixOut` in [SSD](https://github.com/cyriltasse/DDFacet/commit/6ee899829b018c51eb5df0ab7ee5c60178c050dd#diff-89365de6a471d913f764fbe985fd8ae8R87). So now I need another utility that gets makes a mask of the same 10kx10k region. I can do this with pyregion:
```
s="""image
box(center_ra_pix, center_dec_pix, width_pix, height_pix)
"""
r = pyregion.parse(s)
mask = r.get_mask(hdu_flat)
```

Maybe this code should go inside MaskDicoModel eventally.

**Comment by Joshuaalbert** [comment]
Testing on herts now

**Comment by Joshuaalbert** [comment]
Error came up at the mask dico step at this [line](https://github.com/cyriltasse/DDFacet/blob/gain_screens_premerge/DDFacet/Imager/SSD/ClassModelMachineSSD.py#L125).

``` bash
Traceback (most recent call last):
  File "/opt/lofar/DDFacet/bin/DDF.py", line 428, in <module>
    main(OP, messages)
  File "/opt/lofar/DDFacet/bin/DDF.py", line 269, in main
    Imager.Init()
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 187, in Init
    ModelMachine = self.ModConstructor.GiveInitialisedMMFromFile(SubstractModel)
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/ModModelMachine.py", line 59, in GiveInitialisedMMFromFile
    MM.FromDico(DicoSMStacked)
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/SSD/ClassModelMachineSSD.py", line 125, in FromDico
    print>>log, "Reading dico model from dico with %i components"%len(DicoSMStacked["Comp"])
KeyError: 'Comp'

> /opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/SSD/ClassModelMachineSSD.py(125)FromDico()
-> print>>log, "Reading dico model from dico with %i components"%len(DicoSMStacked["Comp"])
```

**Comment by Joshuaalbert** [comment]
However, if I do:
``` python
dico = MyPickle.Load('image_full_ampphase_di_m.NS.DicoModel')
print(dico.keys())
#['ModelShape', 'Comp', 'RefFreq', 'GD', 'SolveParam', 'Type']
```
which shows there is 'Comp' in the DicoModel

**Comment by Joshuaalbert** [comment]
@cyriltasse Shouldn't 
```python
DCompOut[(x1,y1)]=self.DicoSMStacked['Comp'][(x0,y0)]
```
be
``` python
DCompOut['Comp'][(x1,y1)]=self.DicoSMStacked['Comp'][(x0,y0)]
```
at [here](https://github.com/cyriltasse/DDFacet/blob/gain_screens_premerge/DDFacet/Imager/SSD/ClassModelMachineSSD.py#L107)?

**Comment by Joshuaalbert** [comment]
After solving the problems above we now restrict the image domain to approximately 10k pixels in the center. Here is the dirty image of a subtracted dataset with 20k pixels and the region file used to mask. By selecting a image size of 10kx10k just this inner region will be imaged and then herts *should* be able to handle the load. Now testing on a screen on herts.

![Screenshot from 2020-01-04 17-08-39](https://user-images.githubusercontent.com/14807032/71768304-4cf27c00-2f15-11ea-8f09-5aef9cc51354.png)

**Comment by Joshuaalbert** [comment]
@cyriltasse We're getting a 
``` bash
Traceback (most recent call last):
  File "/opt/lofar/DDFacet/bin/DDF.py", line 428, in <module>
    main(OP, messages)
  File "/opt/lofar/DDFacet/bin/DDF.py", line 276, in main
    Imager.main()
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1076, in main
    self.GiveDirty(psf=True, sparsify=sparsify, last_cycle=(NMajor==0))
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 661, in GiveDirty
    ModelImage = self.FacetMachine.setModelImage(self.ModelMachine.GiveModelImage(model_freqs))
  File "/opt/lofar/DDFacet/lib/python2.7/site-packages/DDFacet/Imager/SSD/ClassModelMachineSSD.py", line 296, in GiveModelImage
    ModelImage[ch,pol,x,y]+=Flux
IndexError: index 15986 is out of bounds for axis 3 with size 10125
``` 
Which indicates that the DicoModel with the changed shape doesn't actually have a change shape.

**Comment by Joshuaalbert** [comment]
Solved, restarting tests.

**Comment by Joshuaalbert** [comment]
Ah, so it seems the mask must also be trimmed to the correct size, as it's not automatically handled.

**Comment by Joshuaalbert** [comment]
Finished. The extra subtract takes 2.5 hours and then imaging takes 8.5 hours (down from ~24).
The memory usage over subtract and imaging is this:

![Screenshot from 2020-01-06 11-56-11](https://user-images.githubusercontent.com/14807032/71814038-95c44500-307b-11ea-9171-aee9cccc3bd5.png)
