### ISSUE TITLE
P126+65 doesn't look like previous run 

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/bayes_gain_screens#23]
Must be a book keeping error

**Comment by rvweeren** [comment]
In the kMS solve there is a bug that it pre-applies to raw solutions when solving for the slow solutions. It should have pre-applied the smoothed solutions (probably there is a bug in writing the npz file of the smoothed sols).

**Comment by rvweeren** [comment]
Once this is fixed let me know and I will try another easy field close to P126+65.

**Comment by Joshuaalbert** [comment]
fixed with bd50640f1d959413cbdfa3adc50b2c390bd9c565

**Comment by Joshuaalbert** [comment]
Solve verified.
