### ISSUE TITLE
error with from option do_image_subtract_dds4

### ISSUE THREAD

**Issue by rvweeren** [Joshuaalbert/bayes_gain_screens#27]
```
WARNING: Not mounting /dev/shm (already mounted in container)
WARNING: Not mounting /tmp (already mounted in container)
 - 13:19:31 - ClearSHM                  | Clear shared memory
 - 13:19:31 - ClearSHM                  | Clear Semaphores
 - 13:19:31 - ClearSHM                  | Clear shared dictionaries
usage: pipeline.py [-h] [--no_download NO_DOWNLOAD] [--region_file REGION_FILE]
                   [--ref_dir REF_DIR] [--ref_image_fits REF_IMAGE_FITS]
                   [--auto_resume AUTO_RESUME] [--ncpu NCPU] --obs_num OBS_NUM
                   --archive_dir ARCHIVE_DIR --root_working_dir ROOT_WORKING_DIR
                   --script_dir SCRIPT_DIR [--block_size BLOCK_SIZE]
                   [--deployment_type DEPLOYMENT_TYPE] [--bind_dirs BIND_DIRS]
                   [--lofar_sksp_simg LOFAR_SKSP_SIMG]
                   [--lofar_gain_screens_simg LOFAR_GAIN_SCREENS_SIMG]
                   [--bayes_gain_screens_simg BAYES_GAIN_SCREENS_SIMG]
                   [--bayes_gain_screens_conda_env BAYES_GAIN_SCREENS_CONDA_ENV]
                   [--do_download_archive DO_DOWNLOAD_ARCHIVE]
                   [--do_choose_calibrators DO_CHOOSE_CALIBRATORS]
                   [--do_subtract DO_SUBTRACT] [--do_solve_dds4 DO_SOLVE_DDS4]
                   [--do_slow_solve_dds4 DO_SLOW_SOLVE_DDS4]
                   [--do_smooth_dds4 DO_SMOOTH_DDS4]
                   [--do_tec_inference DO_TEC_INFERENCE]
                   [--do_merge_slow DO_MERGE_SLOW]
                   [--do_image_subtract_dirty DO_IMAGE_SUBTRACT_DIRTY]
                   [--do_image_smooth DO_IMAGE_SMOOTH]
                   [--do_image_dds4 DO_IMAGE_DDS4]
                   [--do_image_subtract_dds4 DO_IMAGE_SUBTRACT_DDS4]
                   [--do_image_smooth_slow DO_IMAGE_SMOOTH_SLOW]
                   [--do_infer_screen DO_INFER_SCREEN]
                   [--do_image_screen DO_IMAGE_SCREEN]
                   [--do_image_screen_slow DO_IMAGE_SCREEN_SLOW]
pipeline.py: error: argument --do_image_subtract_dds4: invalid int value: ''
```

Maybe the singularity image needs updating?

**Comment by Joshuaalbert** [comment]
Ah yes indeed. To manually do it copy the instruct.sh from image_dds4 to another folder and change column to DATA_SUB. And remove the predict dico option. Leave all else the same.JoshOp 14 dec. 2019 1:21 p.m. schreef Reinout van Weeren <notifications@github.com>:WARNING: Not mounting /dev/shm (already mounted in container)
WARNING: Not mounting /tmp (already mounted in container)
 - 13:19:31 - ClearSHM                  | Clear shared memory
 - 13:19:31 - ClearSHM                  | Clear Semaphores
 - 13:19:31 - ClearSHM                  | Clear shared dictionaries
usage: pipeline.py [-h] [--no_download NO_DOWNLOAD] [--region_file REGION_FILE]
                   [--ref_dir REF_DIR] [--ref_image_fits REF_IMAGE_FITS]
                   [--auto_resume AUTO_RESUME] [--ncpu NCPU] --obs_num OBS_NUM
                   --archive_dir ARCHIVE_DIR --root_working_dir ROOT_WORKING_DIR
                   --script_dir SCRIPT_DIR [--block_size BLOCK_SIZE]
                   [--deployment_type DEPLOYMENT_TYPE] [--bind_dirs BIND_DIRS]
                   [--lofar_sksp_simg LOFAR_SKSP_SIMG]
                   [--lofar_gain_screens_simg LOFAR_GAIN_SCREENS_SIMG]
                   [--bayes_gain_screens_simg BAYES_GAIN_SCREENS_SIMG]
                   [--bayes_gain_screens_conda_env BAYES_GAIN_SCREENS_CONDA_ENV]
                   [--do_download_archive DO_DOWNLOAD_ARCHIVE]
                   [--do_choose_calibrators DO_CHOOSE_CALIBRATORS]
                   [--do_subtract DO_SUBTRACT] [--do_solve_dds4 DO_SOLVE_DDS4]
                   [--do_slow_solve_dds4 DO_SLOW_SOLVE_DDS4]
                   [--do_smooth_dds4 DO_SMOOTH_DDS4]
                   [--do_tec_inference DO_TEC_INFERENCE]
                   [--do_merge_slow DO_MERGE_SLOW]
                   [--do_image_subtract_dirty DO_IMAGE_SUBTRACT_DIRTY]
                   [--do_image_smooth DO_IMAGE_SMOOTH]
                   [--do_image_dds4 DO_IMAGE_DDS4]
                   [--do_image_subtract_dds4 DO_IMAGE_SUBTRACT_DDS4]
                   [--do_image_smooth_slow DO_IMAGE_SMOOTH_SLOW]
                   [--do_infer_screen DO_INFER_SCREEN]
                   [--do_image_screen DO_IMAGE_SCREEN]
                   [--do_image_screen_slow DO_IMAGE_SCREEN_SLOW]
pipeline.py: error: argument --do_image_subtract_dds4: invalid int value: ''

Maybe the singularity image needs updating?

**Comment by Joshuaalbert** [comment]
Try again?

**Comment by Joshuaalbert** [comment]
Seems like the repo wasn't reinstalled or simg wasn't updated. So closing
