### ISSUE TITLE
Check robustness of smoothing

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/bayes_gain_screens#3]
Sometimes the calibrators have weird errors around them suggesting that the smoothing went wrong. 

There are three smoothing methods to choose from:

- 3 parameter maximum likelihood fit to phase (clock, const, tec)

- 4 parameter fit to gains (2 per real 2 per imaginary)

- Use the tec inference to smooth nearest neighbours.

- [ ] Check robustness of all three on simularted gains

- [ ] Produce a DDS4_smoothed image of several nights with each method

**Comment by rvweeren** [comment]
It seems some outliers are propagating into the smoothed phase solutions, see this example of the highest frequencies there are some red colored phases. (top raw phases, bottom smoothed phases by Josh)

<img width="596" alt="image" src="https://user-images.githubusercontent.com/3879473/70319906-bc485380-1823-11ea-9a7e-b5967f39a77f.png">

**Comment by Joshuaalbert** [comment]
I now flag the top 3 largest residuals. How shall we test this? If you run the pipeline with only the do_smooth_dds4=2 and all else 0 then it will replace the smoothed000 solset with a new one with this flagging method.
