### ISSUE TITLE
Smoothed + slow seem not to be applied

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/bayes_gain_screens#7]
Oddly it seems the screen improves between calibrators but not at calibrators, therefore the smooth and slow are not being applied. Must be a book keeping error.

**Comment by rvweeren** [comment]
My run finished. There is an improvement in my images from smooth to smooth_low so that is encouraging. Still images look bad good compared to DR2. I think we need to look at the "reference P126+65" first before continuing with more difficult fields.

**Comment by Joshuaalbert** [comment]
P126+65 screen_slow done tomorrow. Also, if I recall, your ionosphere was crazy in that observation. Both yours and Tims. But Martin's was well-behaved, and we saw some nastiness there upon applying screen. I think his image was made prior to bug fixes though which should have fixed the problem. So I think smoothed and slow are being applied and I'll close this.
